name: test

on:
  pull_request:
  push:

jobs:
  test36:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Run Tests
        uses: buildtool/build-action@v1
        with:
          docker-build-args: '--build-arg python_version=3.6'
          dockerfile: Dockerfile.test
  test37:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Run Tests
        uses: buildtool/build-action@v1
        with:
          docker-build-args: '--build-arg python_version=3.7'
          dockerfile: Dockerfile.test
