name: test

on:
  pull_request:
  push:

jobs:
  test36:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        uses: ./.github/actions/test
        env:
          PYTHON_VERSION: '3.6'
  test37:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Tests
        uses: ./.github/actions/test
        env:
          PYTHON_VERSION: '3.7'
